python convert_standard_format.py \
    -i /home/efs/nwang60/datasets/biomedica_webdataset_glm_generated_qwen_verified_VQA_parquet_25k_filtered_13k_subset1k/biomedica_webdataset_glm_generated_qwen_verified_VQA_json_25k_filtered_mean9670_13k_rebalanced_subset1k.parquet \
    -o /home/efs/nwang60/datasets/medvlsynther_std/biomedica_webdataset_glm_generated_qwen_verified_VQA_parquet_25k_filtered_13k_subset1k/biomedica_webdataset_glm_generated_qwen_verified_VQA_json_25k_filtered_mean9670_13k_rebalanced_subset1k.parquet

python convert_standard_format.py \
    -i /home/efs/nwang60/datasets/biomedica_webdataset_glm_generated_qwen_verified_VQA_parquet_25k_filtered_13k_subset2k/biomedica_webdataset_glm_generated_qwen_verified_VQA_json_25k_filtered_mean9670_13k_rebalanced_subset2k.parquet \
    -o /home/efs/nwang60/datasets/medvlsynther_std/biomedica_webdataset_glm_generated_qwen_verified_VQA_parquet_25k_filtered_13k_subset2k/biomedica_webdataset_glm_generated_qwen_verified_VQA_json_25k_filtered_mean9670_13k_rebalanced_subset2k.parquet

python convert_standard_format.py \
    -i /home/efs/nwang60/datasets/biomedica_webdataset_glm_generated_qwen_verified_VQA_parquet_25k_filtered_13k_subset5k/biomedica_webdataset_glm_generated_qwen_verified_VQA_parquet_25k_filtered_13k_subset5k.parquet \
    -o /home/efs/nwang60/datasets/medvlsynther_std/biomedica_webdataset_glm_generated_qwen_verified_VQA_parquet_25k_filtered_13k_subset5k/biomedica_webdataset_glm_generated_qwen_verified_VQA_parquet_25k_filtered_13k_subset5k.parquet

python convert_standard_format.py \
    -i /home/efs/nwang60/datasets/biomedica_webdataset_glm_generated_qwen_verified_VQA_parquet_25k_filtered_13k_subset10k/biomedica_webdataset_glm_generated_qwen_verified_VQA_json_25k_filtered_mean9670_13k_rebalanced_subset10k.parquet \
    -o /home/efs/nwang60/datasets/medvlsynther_std/biomedica_webdataset_glm_generated_qwen_verified_VQA_parquet_25k_filtered_13k_subset10k/biomedica_webdataset_glm_generated_qwen_verified_VQA_json_25k_filtered_mean9670_13k_rebalanced_subset10k.parquet

python convert_standard_format.py \
    -i /home/efs/nwang60/datasets/biomedica_webdataset_glm_generated_qwen_verified_VQA_parquet_25k_filtered_13k/biomedica_webdataset_glm_generated_qwen_verified_VQA_parquet_25k_filtered_13k.parquet \
    -o /home/efs/nwang60/datasets/medvlsynther_std/biomedica_webdataset_glm_generated_qwen_verified_VQA_parquet_25k_filtered_13k/biomedica_webdataset_glm_generated_qwen_verified_VQA_parquet_25k_filtered_13k.parquet

python convert_standard_format.py \
    -i /home/efs/nwang60/datasets/biomedica_webdataset_qwen_generated_glm_verified_VQA_parquet_25k_filtered_13k_subset5k/biomedica_webdataset_qwen_generated_glm_verified_VQA_parquet_25k_filtered_13k_subset5k.parquet \
    -o /home/efs/nwang60/datasets/medvlsynther_std/biomedica_webdataset_qwen_generated_glm_verified_VQA_parquet_25k_filtered_13k_subset5k/biomedica_webdataset_qwen_generated_glm_verified_VQA_parquet_25k_filtered_13k_subset5k.parquet

python convert_standard_format.py \
    -i /home/efs/nwang60/datasets/biomedica_webdataset_internvl_generated_glm_verified_VQA_parquet_25k_filtered_13k_subset5k/biomedica_webdataset_internvl_generated_glm_verified_VQA_parquet_25k_filtered_13k_subset5k.parquet \
    -o /home/efs/nwang60/datasets/medvlsynther_std/biomedica_webdataset_internvl_generated_glm_verified_VQA_parquet_25k_filtered_13k_subset5k/biomedica_webdataset_internvl_generated_glm_verified_VQA_parquet_25k_filtered_13k_subset5k.parquet

python convert_standard_format.py \
    -i /home/efs/nwang60/datasets/biomedica_webdataset_glm_generated_glm_verified_VQA_parquet_25k_filtered_13k_subset5k/biomedica_webdataset_glm_generated_glm_verified_VQA_parquet_25k_filtered_13k_subset5k.parquet \
    -o /home/efs/nwang60/datasets/medvlsynther_std/biomedica_webdataset_glm_generated_glm_verified_VQA_parquet_25k_filtered_13k_subset5k/biomedica_webdataset_glm_generated_glm_verified_VQA_parquet_25k_filtered_13k_subset5k.parquet

python convert_standard_format.py \
    -i /home/efs/nwang60/datasets/biomedica_webdataset_glm_generated_glm_verified_VQA_parquet_25k_without_verifier_subset5k/biomedica_webdataset_glm_generated_glm_verified_VQA_parquet_25k_without_verifier_subset5k.parquet \
    -o /home/efs/nwang60/datasets/medvlsynther_std/biomedica_webdataset_glm_generated_glm_verified_VQA_parquet_25k_without_verifier_subset5k/biomedica_webdataset_glm_generated_glm_verified_VQA_parquet_25k_without_verifier_subset5k.parquet

python convert_standard_format.py \
    -i /home/efs/nwang60/datasets/biomedica_webdataset_glm_generated_pmc_VQA_parquet_25k_rebalanced_subset5k/biomedica_webdataset_glm_generated_pmc_VQA_parquet_25k_rebalanced_subset5k.parquet \
    -o /home/efs/nwang60/datasets/medvlsynther_std/biomedica_webdataset_glm_generated_pmc_VQA_parquet_25k_rebalanced_subset5k/biomedica_webdataset_glm_generated_pmc_VQA_parquet_25k_rebalanced_subset5k.parquet

python convert_standard_format.py \
    -i /home/efs/nwang60/datasets/biomedica_webdataset_glm_generated_qwen_verified_VQA_parquet_25k_filtered_mean9670_13k_rebalanced_subset_cot_rebalanced_7k_subset5k/biomedica_webdataset_glm_generated_qwen_verified_VQA_parquet_25k_filtered_mean9670_13k_rebalanced_subset_cot_rebalanced_7k_subset5k.parquet \
    -o /home/efs/nwang60/datasets/medvlsynther_std/biomedica_webdataset_glm_generated_qwen_verified_VQA_parquet_25k_filtered_mean9670_13k_rebalanced_subset_cot_rebalanced_7k_subset5k/biomedica_webdataset_glm_generated_qwen_verified_VQA_parquet_25k_filtered_mean9670_13k_rebalanced_subset_cot_rebalanced_7k_subset5k.parquet






