python image_contamination_report.py \
  --train "/opt/dlami/nvme/nwang60/datasets/MVT-synthesis/biomedica_webdataset_glm_generated_qwen_verified_VQA_parquet_25k_filtered_13k_subset10k/*.parquet" \
  --test  "/opt/dlami/nvme/nwang60/datasets/MedVLThinker-Eval/data/*.parquet" \
  --run_embed \
  --device cuda \
  --batch_size 128 \
  --topk 5 \
  --cos_thr 0.88 \
  --tau_list "0.85,0.88,0.90" \
  --exclude_same_id \
  --out_dir image_embedding_ours_testset